### ISSUE TITLE
Clean up help text when run with no flags

### ISSUE THREAD

**Issue by PylotLight** [atterpac/refresh#3]
please assign to me.

**Comment by atterpac** [comment]
I believe the ugly logs are from switching log/slog where so some debug levels are duped cause they didn't exist in log so were printed.
The errors at start up can be found in ./engine/config.go

**Comment by PylotLight** [comment]
soz, looks like you already made changes here, all I wanted to suggest/see was some nicer formatting like this. Which I assume you can do with the custom slogger thing. 
![image](https://github.com/atterpac/refresh/assets/7006124/44950690-30d6-4b56-95f4-6247f1d0bef1)
